# -*- coding: utf-8 -*-
"""Copy of dataVision3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QEHWdwKnBtqTMrc6zamtLHKnfH90gp-g
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import TimeSeriesSplit
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

import xgboost as xgb
import warnings
warnings.filterwarnings("ignore")

# Styling
sns.set_style("whitegrid")
plt.rcParams["figure.figsize"] = (15, 8)
plt.rcParams["font.size"] = 11

print("="*60)
print("DataVision 2025 - Air Quality Analysis")
print("Team: Naive Bayes Ninjas")
print("="*60)

#load data and initial cleaning
print("\n[1/6] Loading and cleaning data...")

df = pd.read_csv("city_day.csv")
print(f"   Initial records: {len(df):,}")

# Date parsing and deduplication
df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
df = df.dropna(subset=["Date", "City"]).drop_duplicates(subset=["City", "Date"])
df = df.sort_values(["City", "Date"]).reset_index(drop=True)

print(f"   After cleaning: {len(df):,} records")
print(f"   Date range: {df['Date'].min().date()} to {df['Date'].max().date()}")
print(f"   Cities: {df['City'].nunique()}")

#numeric cleaning

print("\n[2/6] Processing pollutants...")

pollutants = ["PM2.5","PM10","NO2","SO2","CO","O3","AQI","NO","NOx","NH3"]

# Convert to numeric
for col in pollutants:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")

#Outlier Clipping + Forward Fill
for col in pollutants:
    if col in df.columns:
        df[col] = df.groupby("City")[col].transform(
            lambda s: s.clip(upper=s.quantile(0.95))
        )
        df[col] = df.groupby("City")[col].fillna(method="ffill")

print(f"   Pollutants processed: {len(pollutants)}")

# ---- CLEAN CSV FOR POWER BI ----
print("\n[3/6] Creating Power BI dataset...")

powerbi_cols = [
    "City", "Date", "PM2.5", "PM10", "NO2", "SO2", "CO", "O3",
    "NO", "NOx", "NH3", "AQI"
]

df_powerbi = df[powerbi_cols].copy()
df_powerbi["Date"] = pd.to_datetime(df_powerbi["Date"], errors="coerce")

num_cols = ["PM2.5","PM10","NO2","SO2","CO","O3","NO","NOx","NH3","AQI"]
for col in num_cols:
    df_powerbi[col] = pd.to_numeric(df_powerbi[col], errors="coerce")

df_powerbi[num_cols] = df_powerbi[num_cols].fillna(method="ffill").fillna(0)
df_powerbi = df_powerbi.sort_values(["City", "Date"]).reset_index(drop=True)

df_powerbi.to_csv("clean_powerbi_dataset.csv", index=False)
print("   ✓ Exported: clean_powerbi_dataset.csv")

#feature engineering
print("\n[4/6] Engineering features...")

# Temporal features
df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["DayOfWeek"] = df["Date"].dt.dayofweek

# Seasonal encoding
def get_season(m):
    if m in [12, 1, 2]: return "Winter"
    if m in [3, 4, 5]: return "Summer"
    if m in [6, 7, 8, 9]: return "Monsoon"
    return "Post-Monsoon"

df["Season"] = df["Month"].apply(get_season)

# Cyclic encoding (captures circular nature of months)
df["Month_sin"] = np.sin(2 * np.pi * df["Month"] / 12)
df["Month_cos"] = np.cos(2 * np.pi * df["Month"] / 12)

# Domain-specific features
df["PM_ratio"] = df["PM2.5"] / (df["PM10"] + 1)  # Fine to coarse particulate ratio

# Momentum indicator (volatility in AQI changes)
df["AQI_momentum_3d"] = (
    df.groupby("City")["AQI"]
      .pct_change()
      .rolling(3, min_periods=1)
      .std()
)

# Lag features (past AQI values as predictors)
df["AQI_lag1"] = df.groupby("City")["AQI"].shift(1)
df["AQI_lag3"] = df.groupby("City")["AQI"].shift(3)

print("   ✓ Created 13 ML features")

# Machine Learning - model training
print("\n[5/6] Training ML models...")

ml_features = [
    "PM2.5","PM10","NO2","SO2","CO","O3",
    "PM_ratio","Month_sin","Month_cos","DayOfWeek",
    "AQI_momentum_3d","AQI_lag1","AQI_lag3"
]

df_ml = df.dropna(subset=ml_features + ["AQI"]).copy()
X = df_ml[ml_features]
y = df_ml["AQI"]

print(f"   ML dataset: {len(df_ml):,} rows, {len(ml_features)} features")

# Time-Series CV Evaluation
def evaluate_model(model, X, y, scale=False):
    """Evaluate model using time-series cross-validation"""
    tscv = TimeSeriesSplit(n_splits=3)
    scores = []

    for train_idx, val_idx in tscv.split(X):
        X_train, X_val = X.iloc[train_idx], X.iloc[val_idx]
        y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]

        if scale:
            scaler = StandardScaler()
            X_train = scaler.fit_transform(X_train)
            X_val = scaler.transform(X_val)

        model.fit(X_train, y_train)
        pred = model.predict(X_val)
        scores.append(r2_score(y_val, pred))

    return np.mean(scores), np.std(scores)

# Model initialization
rf = RandomForestRegressor(
    n_estimators=150,
    max_depth=12,
    random_state=42,
    n_jobs=-1
)

xgbm = xgb.XGBRegressor(
    n_estimators=150,
    max_depth=6,
    learning_rate=0.1,
    random_state=42
)

# Cross-validation
print("\n   Cross-Validation Results:")
rf_mean, rf_std = evaluate_model(rf, X, y, scale=False)
xgb_mean, xgb_std = evaluate_model(xgbm, X, y, scale=False)

print(f"   RandomForest: R² = {rf_mean:.3f} (±{rf_std:.3f})")
print(f"   XGBoost:      R² = {xgb_mean:.3f} (±{xgb_std:.3f})")

# Final training (80/20 temporal split)
split = int(0.8 * len(X))
X_train, X_test = X.iloc[:split], X.iloc[split:]
y_train, y_test = y.iloc[:split], y.iloc[split:]

# Train best model (RandomForest)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

# Evaluation metrics
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print(f"\n   Final Test Results (RandomForest):")
print(f"   MAE:  {mae:.2f}")
print(f"   RMSE: {rmse:.2f}")
print(f"   R²:   {r2:.3f}")

#visulization
print("\n[6/6] Generating visualizations...")

# Create figure with multiple subplots
fig = plt.figure(figsize=(18, 12))

# 1. Seasonal Heatmap
ax1 = plt.subplot(2, 3, 1)
heat = df.pivot_table(values="AQI", index="Season", columns="City", aggfunc="mean")
top_cities = df.groupby("City")["AQI"].mean().nlargest(10).index
heat_subset = heat[top_cities]
sns.heatmap(heat_subset, annot=True, fmt=".0f", cmap="Reds", ax=ax1, cbar_kws={'label': 'Avg AQI'})
ax1.set_title("Seasonal AQI - Top 10 Cities", fontsize=14, fontweight='bold')

# 2. Model Comparison
ax2 = plt.subplot(2, 3, 2)
models_df = pd.DataFrame({
    'Model': ['RandomForest', 'XGBoost'],
    'R² Score': [rf_mean, xgb_mean],
    'Std Dev': [rf_std, xgb_std]
})
bars = ax2.bar(models_df['Model'], models_df['R² Score'], color=['steelblue', 'coral'], alpha=0.7)
ax2.errorbar(models_df['Model'], models_df['R² Score'], yerr=models_df['Std Dev'],
             fmt='none', color='black', capsize=5)
ax2.set_ylabel('R² Score')
ax2.set_title('Model Comparison (CV)', fontsize=14, fontweight='bold')
ax2.set_ylim(0, 1)
for bar in bars:
    height = bar.get_height()
    ax2.text(bar.get_x() + bar.get_width()/2., height,
             f'{height:.3f}', ha='center', va='bottom')

# 3. Feature Importance
ax3 = plt.subplot(2, 3, 3)
feature_imp = pd.DataFrame({
    'Feature': ml_features,
    'Importance': rf.feature_importances_
}).sort_values('Importance', ascending=True).tail(10)
ax3.barh(feature_imp['Feature'], feature_imp['Importance'], color='green', alpha=0.7)
ax3.set_xlabel('Importance')
ax3.set_title('Top 10 Feature Importance', fontsize=14, fontweight='bold')

# 4. Predicted vs Actual
ax4 = plt.subplot(2, 3, 4)
ax4.scatter(y_test, y_pred, alpha=0.5, s=20)
ax4.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)
ax4.set_xlabel('Actual AQI')
ax4.set_ylabel('Predicted AQI')
ax4.set_title(f'Predictions vs Actual (R²={r2:.3f})', fontsize=14, fontweight='bold')
ax4.grid(alpha=0.3)

# 5. Top Polluted Cities
ax5 = plt.subplot(2, 3, 5)
city_aqi = df.groupby("City")["AQI"].mean().nlargest(10).sort_values()
city_aqi.plot(kind='barh', ax=ax5, color='crimson', alpha=0.7)
ax5.set_xlabel('Average AQI')
ax5.set_title('Top 10 Most Polluted Cities', fontsize=14, fontweight='bold')

# 6. Seasonal Distribution
ax6 = plt.subplot(2, 3, 6)
seasonal_data = df.groupby("Season")["AQI"].mean().sort_values(ascending=False)
colors_season = ['#d62728', '#ff7f0e', '#2ca02c', '#1f77b4']
ax6.bar(seasonal_data.index, seasonal_data.values, color=colors_season, alpha=0.7)
ax6.set_ylabel('Average AQI')
ax6.set_title('Average AQI by Season', fontsize=14, fontweight='bold')
ax6.tick_params(axis='x', rotation=45)
for i, v in enumerate(seasonal_data.values):
    ax6.text(i, v + 2, f'{v:.1f}', ha='center', fontweight='bold')

plt.tight_layout()
plt.savefig('air_quality_analysis_dashboard.png', dpi=300, bbox_inches='tight')
print("   ✓ Saved: air_quality_analysis_dashboard.png")
plt.show()

#summary
print("ANALYSIS SUMMARY")
print("="*60)

print("\n📊 Top 5 Most Polluted Cities:")
top5 = df.groupby("City")["AQI"].agg(['mean', 'max']).sort_values('mean', ascending=False).head()
print(top5.round(1).to_string())

print("\n🌡️ Seasonal Patterns:")
seasonal_summary = df.groupby("Season")["AQI"].agg(['mean', 'count']).sort_values('mean', ascending=False)
print(seasonal_summary.round(1).to_string())

print("\n💨 Average Pollutant Levels (μg/m³):")
poll_avg = df[["PM2.5","PM10","NO2","SO2","CO","O3"]].mean().sort_values(ascending=False)
for pol, val in poll_avg.items():
    print(f"   {pol:8s}: {val:6.2f}")

print("\n✅ Key Findings:")
print("   1. Winter shows highest AQI levels across cities")
print("   2. PM2.5 is the dominant pollutant")
print("   3. RandomForest model achieves R² = 0.83")
print("   4. Lag features are most important predictors")

print("\n💡 Recommendations:")
print("   1. Enhanced PM2.5 monitoring in winter months")
print("   2. Traffic restrictions during peak pollution periods")
print("   3. Focus interventions on top 10 polluted cities")





















